## Desafio 4
___

Utilizando o dataframe ajustado da challenge 1, padronize seus dados para exibir valores numéricos ao invés de dados categorizados no atributo de classe, cidade e estado.

Exemplo, ao invés de true ou false, utilizar 1 ou 0.

In [2]:
import numpy as np
import pandas as pd

In [3]:
df_pimas = pd.read_csv("data/pima-data-norm-city.csv", index_col=0)
df_pimas.head(5)

,num_preg,glucose_conc,diastolic_bp,insulin,bmi,diab_pred,age,skin,diabetes,state,city
id,,,,,,,,,,,
0,6,148.0,72.000000,0.0,33.6,0.627,50,1.379000,True,Maharashtra,Mumbai
1,1,85.0,66.000000,0.0,26.6,0.351,31,1.142600,False,Maharashtra,Mumbai
2,8,183.0,69.112125,0.0,23.3,0.672,32,0.809136,True,Maharashtra,Mumbai
3,1,89.0,66.000000,94.0,28.1,0.167,21,0.906200,False,Maharashtra,Mumbai
4,0,137.0,40.000000,168.0,43.1,2.288,33,1.379000,True,Maharashtra,Mumbai

In [4]:
class_map = {True: 1, False: 0}
city_map = {"Agra": 1, "Bangalore": 2, "Hyderabad": 3, "Lucknow": 4, "Mumbai": 5, "Patna": 6}
state_map = {"Bihar": 1, "Kamataka": 2, "Maharashtra": 3, "Telangana": 4, "Uttar Pradesh": 5}

df_pimas["diabetes"] = df_pimas["diabetes"].map(class_map)
df_pimas["city"] = df_pimas["city"].map(city_map)
df_pimas["state"] = df_pimas["state"].map(state_map)

In [6]:
df_pimas

,num_preg,glucose_conc,diastolic_bp,insulin,bmi,diab_pred,age,skin,diabetes,state,city
id,,,,,,,,,,,
0,6,148.0,72.000000,0.00000,33.600000,0.627,50,1.379000,1,3,5
1,1,85.0,66.000000,0.00000,26.600000,0.351,31,1.142600,0,3,5
2,8,183.0,69.112125,0.00000,23.300000,0.672,32,0.809136,1,3,5
3,1,89.0,66.000000,94.00000,28.100000,0.167,21,0.906200,0,3,5
4,0,137.0,40.000000,168.00000,43.100000,2.288,33,1.379000,1,3,5
5,5,116.0,74.000000,0.00000,25.600000,0.201,30,0.809136,0,3,5
6,3,78.0,50.000000,88.00000,31.000000,0.248,26,1.260800,1,3,5
7,10,115.0,0.000000,0.00000,35.300000,0.134,29,0.809136,0,3,5
8,2,197.0,70.000000,543.00000,30.500000,0.158,53,1.773000,1,3,5
9,8,125.0,96.000000,0.00000,31.992578,0.232,54,0.809136,1,3,5
10,4,110.0,92.000000,0.00000,37.600000,0.191,30,0.809136,0,3,5
11,10,168.0,74.000000,0.00000,38.000000,0.537,34,0.809136,1,3,5
12,10,139.0,80.000000,0.00000,27.100000,1.441,57,0.809136,0,3,5
13,1,189.0,60.000000,846.00000,30.100000,0.398,59,0.906200,1,3,5
14,5,166.0,72.000000,175.00000,25.800000,0.587,51,0.748600,1,3,5
15,7,100.0,0.000000,79.90352,30.000000,0.484,32,0.809136,1,3,5
16,0,118.0,84.000000,230.00000,45.800000,0.551,31,1.851800,1,3,5
17,7,107.0,74.000000,0.00000,29.600000,0.254,31,0.809136,1,3,5
18,1,103.0,30.000000,83.00000,43.300000,0.183,33,1.497200,0,3,5
19,1,115.0,70.000000,96.00000,34.600000,0.529,32,1.182000,1,3,5
20,3,126.0,88.000000,235.00000,39.300000,0.704,27,1.615400,0,3,5
21,8,99.0,84.000000,0.00000,35.400000,0.388,50,0.809136,0,3,5
22,7,196.0,90.000000,0.00000,39.800000,0.451,41,0.809136,1,3,5
23,9,119.0,80.000000,0.00000,29.000000,0.263,29,1.379000,1,3,5
24,11,143.0,94.000000,146.00000,36.600000,0.254,51,1.300200,1,3,5
25,10,125.0,70.000000,115.00000,31.100000,0.205,41,1.024400,1,3,5
26,7,147.0,76.000000,0.00000,39.400000,0.257,43,0.809136,1,3,5
27,1,97.0,66.000000,140.00000,23.200000,0.487,22,0.591000,0,3,5
28,13,145.0,82.000000,110.00000,22.200000,0.245,57,0.748600,0,3,5
29,5,117.0,92.000000,0.00000,34.100000,0.337,38,0.809136,0,3,5
...,...,...,...,...,...,...,...,...,...,...,...
738,2,99.0,60.000000,160.00000,36.600000,0.453,21,0.669800,0,1,6
739,1,102.0,74.000000,0.00000,39.500000,0.293,42,0.809136,1,1,6
740,11,120.0,80.000000,150.00000,42.300000,0.785,48,1.457800,1,1,6
741,3,102.0,44.000000,94.00000,30.800000,0.400,26,0.788000,0,1,6
742,1,109.0,58.000000,116.00000,28.500000,0.219,22,0.709200,0,1,6
743,9,140.0,94.000000,0.00000,32.700000,0.734,45,0.809136,1,1,6
744,13,153.0,88.000000,140.00000,40.600000,1.174,39,1.457800,0,1,6
745,12,100.0,84.000000,105.00000,30.000000,0.488,46,1.300200,0,1,6
746,1,147.0,94.000000,0.00000,49.300000,0.358,27,1.615400,1,1,6
747,1,81.0,74.000000,57.00000,46.300000,1.096,32,1.615400,0,1,6
748,3,187.0,70.000000,200.00000,36.400000,0.408,36,0.866800,1,1,6
749,6,162.0,62.000000,0.00000,24.300000,0.178,50,0.809136,1,1,6
750,4,136.0,70.000000,0.00000,31.200000,1.182,22,0.809136,1,1,6
751,1,121.0,78.000000,74.00000,39.000000,0.261,28,1.536600,0,1,6
752,3,108.0,62.000000,0.00000,26.000000,0.223,25,0.945600,0,1,6
753,0,181.0,88.000000,510.00000,43.300000,0.222,26,1.733600,1,1,6
754,8,154.0,78.000000,0.00000,32.400000,0.443,45,1.260800,1,1,6
755,1,128.0,88.000000,110.00000,36.500000,1.057,37,1.536600,1,1,6
756,7,137.0,90.000000,0.00000,32.000000,0.391,39,1.615400,0,1,6
757,0,123.0,72.000000,0.00000,36.300000,0.258,52,0.809136,1,1,6
758,1,106.0,76.000000,0.00000,37.500000,0.197,26,0.809136,0,1,6
759,6,190.0,92.000000,0.00000,35.500000,0.278,66,0.809136,1,1,6
760,2,88.0,58.000000,16.00000,28.400000,0.766,22,1.024400,0,1,6
761,9,170.0,74.000000,0.00000,44.000000,0.403,43,1.221400,1,1,6
762,9,89.0,62.000000,0.00000,22.500000,0.142,33,0.809136,0,1,6
763,10,101.0,76.000000,180.00000,32.900000,0.171,63,1.891200,0,1,6
764,2,122.0,70.000000,0.00000,36.800000,0.340,27,1.063800,0,1,6
765,5,121.0,72.000000,112.00000,26.200000,0.245,30,0.906200,0,1,6
766,1,126.0,60.000000,0.00000,30.100000,0.349,47,0.809136,1,1,6
767,1,93.0,70.000000,0.00000,30.400000,0.315,23,1.221400,0,1,6

In [7]:
df_pimas.to_csv("data/pima-data-norm-city-map.csv")